# Site
repository: ChrisGalliano/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christian Galliano
title: Senior PHP Developer
email: christian@galliano.info

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  ChrisGalliano
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chris_galliano
linkedin_username: chris-galliano
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
## - title: galliano.info
#  icon: fas fa-globe
#  url: https://galliano.info
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi there! My name is Christian, and I am a senior PHP developer with 8+ years of experience in the field. I work on a high-loaded international classified portal and have a knack for technologies like <mark>PHP</mark>, <mark>MySQL</mark>, <mark>Elasticsearch</mark>, <mark>Redis</mark>, and <mark>IntelliJ Platform</mark>. When I'm not coding, I like to give new productivity techniques a crack, travel to new spots, and enjoy hobbies like cooking, photography, and strumming the ol' ukulele.
  
  I'm always keen to give new things a go and have a bit of fun, so if you want to chat about software development or just want to hear some woeful ukulele covers, don't be shy - give me a shout!

  Nationality: Ukranian
  
  Current location: Thailand
  
  Age: 29

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - PHP
          - MySQL
          - Elasticsearch
          - Redis
          - Memcached
          - XDebug
          - Git
      - layout: left
        title: Complimentary
        description: | # this will include new lines to allow paragraphs
          - IntelliJ Platform (Java & Kotlin)
          - AWS: SES, SQS, SNS
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - TypeScript
          - Gulp, Webpack
          - SCSS
      - layout: left
        title: Languages
        description: | # this will include new lines to allow paragraphs
          - Ukrainian (native)
          - Russian (fluent)
          - English (upper-intermediate, professional working)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linemedia - online marketing and sales
        link: linemedia.com
        # link_text: boringcompany.com
        sub_title: Tech Lead / Senior PHP Developer
        caption: March 2016 - Present
        quote: >
          The main company product is a high-loaded international classified portal with complex server infrastructure, self-written CRM, internal and external APIs.
        description: | # this will include new lines to allow paragraphs
          - Collaborating with cross-functional teams to implement the entire software development lifecycle, including requirements gathering, design, implementation, testing, deployment, and maintenance of software solutions
          - Improving the technical state of the project by introducing code quality tools, implementing new code inspections, and overseeing the refactoring of outdated project modules
          - Led and mentored junior developers, and conducted code reviews
          - Developing and maintaining database systems using MySQL, optimizing database performance, and utilizing tools such as "pt-online-schema-change"
          - Utilizing Elasticsearch and Redis to improve search and caching performance
          - Integrating with third-party services and APIs
          - Working with AWS services such as SES, SQS, and SNS
          - Lecturing on various topics related to PHP development, including Generics, code structures, and the PhpStorm IDE
          - Developing a plugin for the PhpStorm IDE that provides various features for the internal project framework, including code inspections, completions, type hinting, and line markers

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Interregional Academy of Personnel Management
        caption: 2009 - 2013
        sub_title: Bachelor's degree, Information Technology
        description: | # this will include new lines to allow paragraphs
          While I was studying for my Bachelor's degree, I'll admit that I was a bit of a slacker at first. I just couldn't seem to get motivated to hit the books. But then I discovered web development, and it was like a lightbulb went off in my head. I was all like, "Yo, this stuff is lit!" and suddenly I was putting in the hours and getting my grind on. It was a complete 180 from where I was before.
          I am so hyped that the time I spent at the Interregional Academy of Personnel Management opened up the world of web development to me.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Aside from my work technical skills and experiences, I'm also a bit of a productivity nerd. I love using apps, like Notions, Things, and Obsidian to stay organized and on top of my work, and I'm always looking for new techniques like the 52/17 rule, GTD method, and PARA method. I'm always open to trying new ways of getting things done (although I'll admit, I'm still trying to figure out how to make the Pomodoro technique work for me).
  
      Outside of work, I've got a soft spot for Asian culture and love nothing more than traveling to new and exciting places, especially if there are some delicious cuisine and good waves for surfing. I also enjoy hobbies like cooking, photography, and playing the ukulele in my free time (tbh my ukulele skills are still a work in progress). And while I may not be the most talented surfer or ukulele player out there, I love trying new things and having fun. So if you want to chat about anything from software development to the best spots for surfing (or just want to hear some terrible ukulele covers), don't hesitate to reach out!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
